# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fae75f4c21a1ada9804a7d79703e8f471279e4cec4d4180e4e66ed6cd2ed3a7a75d8112b4834aa70fe51cef9b03717d6901e7dbc95c86a449aee4d8b55740af

test:
  secret_key_base: 89ba7f994ce1b9db1a7d66b7a92a223b48381b5babb1675f4c454ae97dbebfb6d3e499326045e8bc517fa52dc042153aa25c80891e660bd882670a592f6b9f0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
